// lib/bingo.ts

export type BingoCard = {
  id: string;
  grid: string[][]; // 5x5
};

export const BINGO_ITEMS: string[] = [
  // ==== DEFAULTS (edit this list whenever you want new defaults) ====
  // Keep these UNIQUE. Duplicates get removed in the UI anyway.
  "Joe’s Grows",
  "Harvest Heroes",
  "Solo Cup",
  "Germinated Seed",
  "LED Light",
  "Fan",
  "pH Pen",
  "Nutrients Fed",
  "Cal-Mag",
  "Cal-Mag Deficiency",
  "Sticky Trichomes",
  "Training Wires / LST",
  "Runoff Check",
  "pH Issues",
  "Watered Today",
  "Flush Time",
  "Leaf Tucking",
  "Bud Sites Showing",
  "Pistils Showing",
  "Recharge / Microbes",
  "EC/PPM Check",
  "Tent Zip Open",
  "New Growth",
  "Harvest Ready",
  "Defoliation",
  "Lollipop",
  "Topping",
  "FIM",
  "Supercrop",
  "Trellis Net",
  "Support Stakes",
  "Stretch Week",
  "Pre-Flower",
  "Trichomes",
  "Amber Check",
  "Humidity Spike",
  "Heat Stress",
  "Cold Snap",
  "Lights On",
  "Lights Off",
  "Top Off",
  "Reservoir Change",
  "Root Check",
  "Nute Burn",
  "Lockout",
  "Funky Terps",
  "Powdery Mildew",
  "Fungus Gnats",
  "Spider Mites",
  "Thrips",
  "Aphids",
  "IPM Spray",
  "Sticky Traps",
  "Neem Smell",
  "Sticky Scissors",
  "Trim Jail",
  "Harvest Day",
  "Wet Trim",
  "Dry Trim",
  "Hang Dry",
  "Dry Room Check",
  "Jar Time",
  "Burp Jars",
  "Cure Check",
  "Smoke Test",
  "Growmie Advice",
  "New Genetics",
  "Seed Pop",
  "Clone Day",
  "Transplant",
  "Training Day",
  "Pray for Yield",
  "Send Pics",
  "Winner
